version: '3'
services:
  tri-provider:
    image: htynkn/tri-provider:1.0-SNAPSHOT
    environment:
      DUBBO_ZOOKEEPER_ADDRESS: zookeeper
    depends_on:
      - data-init
  tri-consumer:
    image: htynkn/tri-consumer:1.0-SNAPSHOT
    environment:
      DUBBO_ZOOKEEPER_ADDRESS: zookeeper
    depends_on:
      - data-init
  data-init:
    image: htynkn/data-init:1.0-SNAPSHOT
    environment:
      DUBBO_ZOOKEEPER_ADDRESS: zookeeper
    depends_on:
      - zookeeper
  zookeeper:
    image: bitnami/zookeeper:3.7.0
    environment:
      ALLOW_ANONYMOUS_LOGIN: 'yes'
