name: Docker publish

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login in github packages
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login https://docker.pkg.github.com -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    - uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn -B package
    - name: Push images
      run: |
        docker push htynkn/data-init:1.0-SNAPSHOT
        docker push htynkn/tri-consumer:1.0-SNAPSHOT
        docker push htynkn/tri-old-consumer:1.0-SNAPSHOT
        docker push htynkn/tri-provider:1.0-SNAPSHOT
        docker push htynkn/tri-old-provider:1.0-SNAPSHOT
